[package]
name = "portscan-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
num_cpus = "1"
# windows = { version = "0.62.2", features = ["Win32_UI_WindowsAndMessaging"] }
ipnetwork = "0.20"
futures = "0.3"
