[package]
name = "mg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "2"
chrono = "0.4.42"
windows-sys = { version = "0.61.2", features = [
  "Win32_Storage_FileSystem",
  "Win32_System_Registry",
  "Win32_System_Com",
  "Win32_System_Ole",
  "Win32_System_Variant",
  "Win32_UI_Shell",
] }
memmap2 = "0.9.9"
